PUT http://localhost:8080/invest/update
Content-type: application/json

{
  "id": 2,
  "securities": [
    {
      "id": 2,
      "invest_id": 2,
      "symbol": "AAPL",
      "type": "Stock",
      "quantity": 3
    }
  ]
}